# Generated by Django 4.2.11 on 2024-06-19 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_satsuser_sats_balance'),
        ('events', '0015_event_org_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user_magic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances_by_magic', to='api.satsuser', to_field='magic_string'),
        ),
    ]
