# Generated by Django 4.2.11 on 2024-06-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_attendance_user_magic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user_magic',
        ),
        migrations.AddField(
            model_name='attendance',
            name='phone_number',
            field=models.TextField(null=True),
        ),
    ]
